### ISSUE TITLE
Delnar's Eye Gouger does not dispell magic

### ISSUE THREAD

**Issue by riklaunim** [Pocket-Plane-Group/Under-Respresented_Items#1]
Tested on BG2:EE 2.6.6.0 and the UR v8. The dart displays the effect or dispel magic but nothing happens - ally or enemy will not get any effects dispelled while hit from staff of the magi clears all effects (like fireshields and alike).

**Comment by CamDawg** [comment]
Yep, I see it. The darts are using the dispel formula (using the caster level) for a chance to dispel rather than the always dispel option. I'll get it fixed.

**Comment by CamDawg** [comment]
Fixed in this commit, closing:

https://github.com/Pocket-Plane-Group/Under-Respresented_Items/commit/00000cddbb57b1e2894d9e5731a684392da593ea
